### ISSUE TITLE
Calibration of the accelerometer

### ISSUE THREAD

**Issue by capitancambio** [neuralcubes/neuralates#28]

**Comment by jmanart** [comment]
Beware both the tap in the interface and the accelerometer reading from the data bus may happen at different times. Otherwise just keep the latest and subtract readings.

Should we have a reset accelerometer to zero button?

**Comment by monchote** [comment]
@jmanart What's the difference between calibrate and reset to zero?

**Comment by jmanart** [comment]
I was thinking of having the ability to reset everything to have the raw readings again in case we run into a strange situation. When we calibrate it the first time we will loose the ability to completely go to the initial situation.
The same button would reset the score for a new player ( #27 )
